# Lab 18 - 1828258 Pranav Shekhar

## 1. Write a NumPy program to compute the cross product of two given vectors.

In [2]:
import numpy as np
p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])
print("Original Matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("Cross product of the two vectors(p, q):")
print(result1)
print("Cross product of the two vectors(q, p):")
print(result2)

Original Matrix:
[[1 0]
 [0 1]]
[[1 2]
 [3 4]]
Cross product of the two vectors(p, q):
[ 2 -3]
Cross product of the two vectors(q, p):
[-2  3]



## 2. Write a NumPy program to compute the determinant of a given square array.

In [4]:
import numpy as np
from numpy import linalg
a = np.array([[1, 0], [1, 2]])
print("Original Array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

Original Array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


## 3. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [6]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


## 4. Write a NumPy program to get the indices of the sorted elements of a given array.

In [7]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


## 5. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15. 
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

In [8]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("Number of attempts in the examination is less than 2 and score greater than 15 :")
print(df[(df['attempts'] < 2) & (df['score'] > 15)])

Number of attempts in the examination is less than 2 and score greater than 15 :
    name  score  attempts qualify
j  Jonas   19.0         1     yes


## 6. Write a Pandas program to check whether only lower case or upper case is present in a given column of a DataFrame.

In [9]:
import pandas as pd
df = pd.DataFrame({
    'company_code': ['ABCD','EFGF', 'hhhh', 'abcd', 'EAWQaaa'],
    'date_of_sale ': ['12/05/2002','16/02/1999','25/09/1998','12/02/2022','15/09/1997'],
    'sale_amount': [12348.5, 233331.2, 22.5, 2566552.0, 23.0]})

print("Original DataFrame:")
print(df)
print("\nIs lower (company_code)?")
df['company_code_ul_cases'] = list(map(lambda x: x.islower(), df['company_code']))
print(df)
print("\nIs Upper (company_code)?")
df['company_code_ul_cases'] = list(map(lambda x: x.isupper(), df['company_code']))
print(df)

Original DataFrame:
  company_code date_of_sale   sale_amount
0         ABCD    12/05/2002      12348.5
1         EFGF    16/02/1999     233331.2
2         hhhh    25/09/1998         22.5
3         abcd    12/02/2022    2566552.0
4      EAWQaaa    15/09/1997         23.0

Is lower (company_code)?
  company_code date_of_sale   sale_amount  company_code_ul_cases
0         ABCD    12/05/2002      12348.5                  False
1         EFGF    16/02/1999     233331.2                  False
2         hhhh    25/09/1998         22.5                   True
3         abcd    12/02/2022    2566552.0                   True
4      EAWQaaa    15/09/1997         23.0                  False

Is Upper (company_code)?
  company_code date_of_sale   sale_amount  company_code_ul_cases
0         ABCD    12/05/2002      12348.5                   True
1         EFGF    16/02/1999     233331.2                   True
2         hhhh    25/09/1998         22.5                  False
3         abcd    12/02/20