# Lab 15 - 1828258 Pranav Shekhar

## 1. Find degree of a polynonial in numpy.

In [28]:
import numpy as np

num = [1,2,3,4]

poly = np.poly1d(num)

print(poly)


deg = poly.order


print(deg)



   3     2
1 x + 2 x + 3 x + 4
3


## 2. WAP to find factorial of a number in numpy.

In [9]:
n = int(input("Enter the number "))

fact = np.math.factorial(n)

print(fact)

120


## 3. WAP to find roots of a Quadratic Equation.

In [14]:
coeff = [1,2,3]

poly = np.poly1d(coeff)

print(poly)

roots = np.roots(coeff)

print(roots)




   2
1 x + 2 x + 3
[-1.+1.41421356j -1.-1.41421356j]


## 4. WAP to print diagonal elements of a matrix.

In [15]:

mat = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]') 
         

diag = mat.diagonal() 
   
print(diag)

[[1 5 9]]


## 5. WAP to find profit or loss for a given CP and SP.

In [23]:
cost = float(input(" Please Enter the Actual Product Price: "))
amount = float(input(" Please Enter the Sales Amount: "))
 
if(cost > amount):
    p = cost - amount
    print("Total Loss Amount = {0}".format(p))
elif(amount > cost):
    p = amount - cost
    print("Total Profit = {0}".format(p))
else:
    print("No Profit No Loss!!!")

Total Profit = 50.0


## 6. WAP to sort the matrix row wise and Column wise.


In [20]:
a = np.array([[1,4], [3,1]])
a.sort(axis=1)

print(a)

a.sort(axis=0)

print(a)

[[1 4]
 [1 3]]
[[1 3]
 [1 4]]
