# Lab 16 - 1828258 Pranav Shekhar

In [32]:
import pandas as pd
import numpy as np

## Q1. WAP to create a dictionary of pandas series and from that create a dataframe and find the transpose of the dataframe.

In [21]:
numbers = {
    1: pd.Series([1, 2, 3]),
    2: pd.Series([4, 5, 6]),
    3: pd.Series([7, 8, 9]),
}

dataFrame = pd.DataFrame(numbers)
dataFrameTranspose = dataFrame.transpose()

print("Data Frame\n")
print(dataFrame, '\n\n')
print("Data Frame Transpose\n")
print(dataFrameTranspose)

Data Frame

   1  2  3
0  1  4  7
1  2  5  8
2  3  6  9 


Data Frame Transpose

   0  1  2
1  1  2  3
2  4  5  6
3  7  8  9


## Q2. Find the number of records in a dataframe.

In [84]:
numbers = {
    1: pd.Series([1, 2, 3]),
    2: pd.Series([4, 5, 6]),
    3: pd.Series([7, 8, 9])
}

dataFrame = pd.DataFrame(numbers)

print("DataFrame:\n")
print(dataFrame)

print("\n\nNumber of records: ", dataFrame.shape[0])

DataFrame:

   1  2  3
0  1  4  7
1  2  5  8
2  3  6  9


Number of records:  3


## Q3. WAP to create a dict with series. Create a dataframe and return the actual data in the DataFrame as an NDarray.

In [35]:
numbers = {
    1: pd.Series([1, 2, 3]),
    2: pd.Series([4, 5, 6]),
    3: pd.Series([7, 8, 9]),
}

dataFrame = pd.DataFrame(numbers)

print("DataFrame:\n")
print(dataFrame)
print("\n")

for i in dataFrame:
    print(np.array(dataFrame[i]))

DataFrame:

   1  2  3
0  1  4  7
1  2  5  8
2  3  6  9


[1 2 3]
[4 5 6]
[7 8 9]


## Q4. WAP to create a dict with series. Create a dataframe and return the first row and the last row.

In [41]:
numbers = {
    1: pd.Series([1, 2, 3]),
    2: pd.Series([4, 5, 6]),
    3: pd.Series([7, 8, 9]),
}

dataFrame = pd.DataFrame(numbers)

print("DataFrame:\n")
print(dataFrame)
print("\n")

print("First Column:\n")
print(dataFrame[1])

print("\n\nLast Column:\n")
print(dataFrame[len(dataFrame)])


DataFrame:

   1  2  3
0  1  4  7
1  2  5  8
2  3  6  9


First Column:

0    1
1    2
2    3
Name: 1, dtype: int64


Last Column:

0    7
1    8
2    9
Name: 3, dtype: int64


## Q5. WAP to iterate rows using itertuples.

In [50]:
numbers = {
    1: pd.Series([1, 2, 3]),
    2: pd.Series([4, 5, 6]),
    3: pd.Series([7, 8, 9]),
}

dataFrame = pd.DataFrame(numbers)

print("DataFrame:\n")
print(dataFrame)
print("\n")

print("Rows","\n")

for row in dataFrame.itertuples():
    print(np.array(row))

DataFrame:

   1  2  3
0  1  4  7
1  2  5  8
2  3  6  9


Rows 

[0 1 4 7]
[1 2 5 8]
[2 3 6 9]


## Q6. WAP to find the length of the string.

In [63]:
strings = {
    1: pd.Series(["Hello", "World", "Python", "Pandas"]),
}

dataFrame = pd.DataFrame(strings)

for row in dataFrame.itertuples():
    print(f"String: '{row._1}', String length: {len(row._1)}")

String: 'Hello', String length: 5
String: 'World', String length: 5
String: 'Python', String length: 6
String: 'Pandas', String length: 6


## Q7. Repeat the values in odd position 3 times in the dataframe.

In [80]:
strings = pd.Series(["Hello", "World", "Python", "Pandas"])

pd.Series([x for i, x in enumerate(list(strings)) if i % 2 != 0]).repeat(3)

0     World
0     World
0     World
1    Pandas
1    Pandas
1    Pandas
dtype: object

## Q8. WAP TO Merge Two DataFrames on Multiple Keys

In [83]:
a = pd.DataFrame({'A':['0', '0', '1','1'],'B':['0', '1', '0','1'], 'v':[True, False, False, True]})
b = pd.DataFrame({'A':['0', '0', '1','1'], 'B':['0', '1', '0','1'],'v':[False, True, True, True]})

result = pd.merge(a, b, on=['A','B'], how='inner', suffixes=['_and', '_or'])

result

A  B  v_and   v_or
0  0  0   True  False
1  0  1  False   True
2  1  0  False   True
3  1  1   True   True