# Lab 14 - 1828258 Pranav Shekhar

## N-Dimensional Array

In [1]:
import numpy as np

a = np.array([1,2,3])

print(a)

[1 2 3]


In [3]:
 b = np.array([[1,2],[3,4]])

print(b)

[[1 2]
 [3 4]]


In [5]:
c = np.array([1,2,3,4], ndmin=2)
print(c)

[[1 2 3 4]]


In [6]:
d = np.array([1,2,3,4], dtype=complex)
print(d)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


## Parameters of data type - numpy.dtype(object, align, copy)

## Slicing

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10,11,12])

print(arr[2:7])

[3 4 5 6 7]


In [11]:
arr = np.arange(10)

s = slice(2,7,2)

print(arr[s])

[2 4 6]


## WAP to slice a single value from a certain array.

In [12]:
arr = np.arange(30)

s = slice(2,3,1)

print(arr[s])

[2]


In [13]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 

print(x)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 

y = x[[0,0,1], [0,1,0]]

z= x[[]]

print(y)

[1 2 3]


## Illustrate integer indexing in a 5 x 3 array.

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]) 

print(x)

y = x[[0,0,1,2], [0,1,0,0]]


print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[1 2 4 7]


## Iteration -  numpy.nditer

In [18]:
a = np.arange(0,100,5)

a = a.reshape(4,5)

print(a)

for num in np.nditer(a):
    print(num)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95


In [23]:
a = np.arange(0,80,5)
a = a.reshape(4,4)
print ('Original array is:')
print (a)
print ('\n')

print ('Transpose of the original array is:')
b = a.T
print (b)
print('\n') 

print ('Sorted in C order:')
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
   print (x),

print ('\n')

print ('Sorted in F-order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x),

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]]


Transpose of the original array is:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]


Sorted in C order:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]
0
20
40
60
5
25
45
65
10
30
50
70
15
35
55
75


Sorted in F-order:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]
0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75


## 1. WAP TO FIND ROUND OFF VALUES OF DECIMAL POINTS.

In [27]:
x = np.array([[1.5555, 2.6666], [3.333333, 4.44444], [5.777777, 6.555555]]) 

print(x)

for num in np.nditer(x):
    print(np.round(num,2))

[[1.5555   2.6666  ]
 [3.333333 4.44444 ]
 [5.777777 6.555555]]
1.56
2.67
3.33
4.44
5.78
6.56


## 2. WAP TO DEMOSNTRATE BASIC ARITHMATIC OPERATIONS ON ARRAY.

In [30]:
a = np.arange(9).reshape(3,3) 


print(a)
print('\n')


b = np.array([10,10,10]) 
print(b) 
print('\n')  

print('Addition')
print(np.add(a,b)) 
print('\n')  

print('Subtraction')
print(np.subtract(a,b)) 
print('\n')  

print('Multiplication') 
print(np.multiply(a,b)) 
print('\n')  

print('Division') 
print(np.divide(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[10 10 10]


Addition
[[10 11 12]
 [13 14 15]
 [16 17 18]]


Subtraction
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]


Multiplication
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


Division
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


## 3. TAKE AN ARRAY WITH ATLEAT 7 INTEGET VALUES AND CALCULATE THEIR RECIPROCAL.

In [31]:
c = np.array([1,2,3,4,5,6,7]) 

print(c)

print("\n")

print("Reciprocal:-")

print(np.reciprocal(c))

[1 2 3 4 5 6 7]


Reciprocal:-
[1 0 0 0 0 0 0]


## 4. FIND THE NTH POWER OF VALUES OF AN ARRAY

In [33]:
n = int(input("Enter the value of n"))

d = np.array([1,2,3,4,5,6,7]) 

print(np.power(d,n))

[  1   8  27  64 125 216 343]


## 5. WAP TO FIND THE PERCENTILE OF ARRAY ELEMENTS.

In [35]:
a=np.arange(0,5)
print(np.percentile(a,25))

1.0


## 6. WAP TO FIND THE MEDIAN OF ARRAY ELEMENT.

In [36]:
b=np.arange(0,10)
print(np.median(b))

4.5


## 7. WAP TO FIND THE AVERAGE, MODE, STANDARD DEVIATION , VARIANCE OF ARRAY ELEMENT

In [38]:
from scipy import stats

a=np.arange(1,20)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

b=[1,2,3,4,5,4,1]

print(stats.mode(b)[0][0])

C:\Users\KIIT\anaconda3\envs\my_personal_lab\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\KIIT\anaconda3\envs\my_personal_lab\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
10.0
5.477225575051661
30.0
1


## 8. IMPLEMRNT ANY ONE SORT USING NUMPY.

In [37]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

[0 1 2 3]
